name: 'LLM code review'
description: 'Query an LLM API to create a code review'

inputs:
  backend:
    default: gemini-2.0
    description: "Language model to query (gemini, mistral, or gh-<GitHub Models model name> (e.g., gh-phi-4, gh-gpt-4o)"
  code-dir:
    default: "coderoot"
  api-key-variable:
    default: LLM_API_KEY
    description: "Name of variable in which API key is stored; must be set in calling workflow"
  reference-owner:
    description: "Owner of authoritative branch (e.g., NOAA-EMC)"
    default: NOAA-EMC
  reference-branch:
    default: ${{ github.event.pull_request.base.ref || 'develop' }}
  context-lines:
    default: 100
  prompt-text:
    default: "Create a code review for the following file diff. Create a bulleted list summarizing the changes, including the inferred purpose of the change, any errors, and suggestions for better approaches if appropriate.\n"
  github-token:
    description: "GitHub token for posting PR comments"

runs:
  using: 'composite'
  steps:

    - name: 'Checkout modified code'
      if: ${{ inputs.code-dir == 'coderoot' }}
      uses: actions/checkout@v4
      with:
        path: coderoot

    - name: 'Get diffs and run query'
      shell: bash
      run: |
        sudo apt-get install pandoc
        cd ${{ inputs.code-dir }}
        mkdir review_by_file
        # Get list of differing files compared with reference URL/branch:
        git remote add reference https://github.com/${{ inputs.reference-owner }}/${{ github.event.repository.name }}
        git remote update reference
        diff_files=$(git diff --name-only reference/${{ inputs.reference-branch }} HEAD)
        # Get diff for each file and query LLM API:
        for file in $diff_files ; do
          if [ ! -f $file ]; then continue ; fi
          filetype=$(file -b $file)
          if [[ " $filetype " =~ " data " ]]; then continue ; fi
          echo -e "${{ inputs.prompt-text }}" > ${file}.diff
          git diff --no-prefix -U${{ inputs.context-lines }} reference/${{ inputs.reference-branch }} HEAD -- $file >> ${file}.diff
          ${{ github.action_path }}/query_llm_api.py ${file}.diff ${file}.review --backend ${{ inputs.backend }} --key-variable ${{ inputs.api-key-variable }}
          pandoc -f commonmark ${file}.review -o ${file}.review.html
          mv ${file}.review.html review_by_file/.
        done

    - name: 'Upload reviews as artifact'
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.backend }}-code-reviews-${{ github.event.repository.name }}-${{ github.sha }}-${{ inputs.reference-branch }}
        path: ${{ inputs.code-dir }}/review_by_file/

    - name: 'Comment PR'
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Here is an artifact with your automated ${{ inputs.backend }} code review (commit ${{ github.sha }}): ${{ steps.upload-artifact.outputs.artifact-url }}'
          })
