name: 'LLM code review'
description: 'Query an LLM API to create a code review'

inputs:
  backend:
    default: gh-gpt-4o
    description: "Language model to query (gemini-2.0, mistral, or gh-<GitHub Models model name> (e.g., gh-phi-4, gh-gpt-4o)"
  code-dir:
    default: "coderoot"
  api-key-variable:
    default: LLM_API_KEY
    description: "Name of variable in which API key is stored; must be set in calling workflow"
  api-key:
    description: "API key"
    default: 'empty'
  reference-owner:
    description: "Owner of authoritative branch (e.g., NOAA-EMC)"
    default: NOAA-EMC
  reference-branch:
    default: ${{ github.event.pull_request.base.ref || 'develop' }}
  context-lines:
    default: 100
  prompt-text:
    default: "Create a code review for the following file diff. Structure the review as 'Summary of Changes,' 'Issues & Possible Errors,' and 'Suggestions' with possible better approaches if appropriate. Focus your review on the new and removed lines indicated by + and - symbols, using the surrounding context to understand the impacts of those changes. These changes are part of the NOAA EMC '${{ github.event.repository.name }}' repository, so please consider the implications of these changes for the rest of the code.\n"
  github-token:
    description: "GitHub token for posting PR comments"
  save-diff-files:
    description: "Save diff files for debugging purposes"
    default: false

runs:
  using: 'composite'
  steps:

    - name: 'Checkout modified code'
      if: ${{ inputs.code-dir == 'coderoot' }}
      uses: actions/checkout@v4
      with:
        path: coderoot

    - name: 'Get diffs and run query'
      shell: bash
      run: |
        if [ "${{ inputs.api-key }}" != 'empty' ]; then
          export ${{ inputs.api-key-variable }}=${{ inputs.api-key }}
        fi
        sudo apt-get --quiet install pandoc
        cd ${{ inputs.code-dir }}
        mkdir review_by_file
        echo "Getting list of differing files compared with reference URL/branch"
        git remote add reference https://github.com/${{ inputs.reference-owner }}/${{ github.event.repository.name }}
        git remote update reference
        diff_files=$(git diff --name-only reference/${{ inputs.reference-branch }} HEAD)
        echo "Getting diff for each file and querying LLM API"
        for file in $diff_files ; do
          if [ ! -f $file ]; then continue ; fi
          filetype=$(file -b $file)
          if [[ " $filetype " =~ " data " ]]; then continue ; fi
          echo -e "${{ inputs.prompt-text }}" > ${file}.diff
          git diff --no-prefix -U${{ inputs.context-lines }} reference/${{ inputs.reference-branch }} HEAD -- $file >> ${file}.diff
          if [ "${{ inputs.save-diff-files }}" == true ]; then
            mkdir -p ${GITHUB_WORKSPACE}/diffs
            cp ${file}.diff ${GITHUB_WORKSPACE}/diffs/.
          fi
          ${{ github.action_path }}/query_llm_api.py ${file}.diff ${file}.review --backend ${{ inputs.backend }} --key-variable ${{ inputs.api-key-variable }}
          pandoc -f commonmark ${file}.review -o ${file}.review.html
          mv ${file}.review.html review_by_file/.
          echo "Processed ${file}"
        done

    - name: 'Upload reviews as artifact'
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.backend }}-code-reviews-${{ github.event.repository.name }}-${{ github.sha }}-${{ inputs.reference-branch }}
        path: ${{ inputs.code-dir }}/review_by_file/

    - name: 'Upload diffs as artifact'
      id: upload-diffs-artifact
      uses: actions/upload-artifact@v4
      if: ${{ inputs.save-diff-files == 'true' }}
      with:
        name: ${{ inputs.backend }}-diffs-${{ github.event.repository.name }}-${{ github.sha }}-${{ inputs.reference-branch }}
        path: ${{ github.workspace }}/diffs

    - name: 'Comment PR'
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Here is an artifact with your automated ${{ inputs.backend }} code review (commit ${{ github.sha }}): ${{ steps.upload-artifact.outputs.artifact-url }}'
          })
